# Generated by Django 5.1.1 on 2024-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vastra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
