# Generated by Django 5.1.1 on 2024-10-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vastra', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
