# Generated by Django 5.1.1 on 2024-12-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vastra', '0003_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
