# Generated by Django 5.1.1 on 2024-12-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vastra', '0004_remove_product_image_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
